### PR TITLE
Wrong parameters passed in dpo.py, generate

### PR DESCRIPTION
**Pull request by ivanfioravanti**
Wrong parameters passed in dpo.py to generate for reference and policy completions.

Refactor sillm training model and model wrapper

This commit includes cosmetic changes to improve readability in the sillm training model and model wrapper, including reformatting function arguments and changing log levels. Some function arguments are also clarified with improved naming, and quantized linear class predicate is streamlined. All changes are non-functional and do not affect execution or output.

### CODE REVIEW

**Comment by armbues** [comment]
What is done about the "wrong parameters passed in dpo.py to generate for reference and policy completions" in this commit? Maybe file an issue together with this?

Changes to improve readability can be argued over and should be done across the whole repository.

**Comment by ivanfioravanti** [comment]
Row 78 and 79 of dpo.py temp and num_tokens params instead of temperature and max_tokens. 
You are totally right we can close this PR and you can fix this easily in Main.
I added/update some docstring too, but not a big issue.

**Comment by armbues** [comment]
Good catch! Looks like the generate parameters were updated in the LLM module but not in DPO. I'll fix it in the main branch for now, but thanks for the contribution 😃 

I would've just merged it if this was an isolated fix for this bug, but the readability changes are a bigger discussion: ask 10 devs and you will get 10 answers on what is better readability... 🙈

**Comment by ivanfioravanti** [comment]
Perfect!

**Pull request closed without merging**
